// The JSON Schema of HDTP's JSON wire objects, generated from hdtp-identity's contract, which both
// of its ports are validated against on every gate run (its js/parity.mjs). A schema written here by
// hand would be a second copy nothing holds; this one is the contract's definitions, copied.
//
//   node schema/gen.mjs           write schema/<version>/schema.json for every version directory
//   node schema/gen.mjs --check   regenerate and fail if a committed file differs (npm run schema:check)
//
// The contract is hdtp-identity's contract/contract.json, found as site/siblings.mjs finds it
// (HDTP_IDENTITY_DIR, else ../hdtp-identity). The objects are the ones the specification defines as
// JSON and the contract defines as a schema: the sealed envelope (§13.1), the signing request
// (§9.1), and the export's manifest and rows (§9.2), with every definition they reference.
// schema/README.md names what is left out and why.
import { existsSync, mkdirSync, readFileSync, writeFileSync } from 'node:fs'
import { join } from 'node:path'
import { identityDir } from '../site/siblings.mjs'
import { root, versions } from '../site/spec-source.mjs'

export const OBJECTS = ['Envelope', 'SigningRequest', 'ExportManifest', 'ContactRow', 'ThreadRow', 'MessageRow']

const refsOf = (node, out = new Set()) => {
  if (node && typeof node === 'object') {
    for (const [k, v] of Object.entries(node)) {
      if (k === '$ref' && typeof v === 'string') out.add(v)
      else refsOf(v, out)
    }
  }
  return out
}

// The schema document for `version`, from the contract's text.
export function schemaFor(contract, version) {
  const defs = contract.$defs
  const picked = new Set()
  const take = (name) => {
    if (picked.has(name)) return
    if (!defs[name]) throw new Error(`the contract has no $defs.${name}`)
    picked.add(name)
    for (const ref of refsOf(defs[name])) {
      const m = /^#\/\$defs\/([A-Za-z0-9]+)$/.exec(ref)
      if (!m) throw new Error(`$defs.${name} references ${ref}, which is not a definition of the contract`)
      take(m[1])
    }
  }
  for (const name of OBJECTS) take(name)
  return {
    $schema: 'https://json-schema.org/draft/2020-12/schema',
    $id: `urn:hdtp:schema:${version}`,
    title: `HDTP ${version}: the JSON objects of the wire`,
    description: `Generated by schema/gen.mjs from hdtp-identity's contract/contract.json (spec ${contract.spec}); do not edit. The objects: ${OBJECTS.join(', ')}.`,
    $defs: Object.fromEntries([...picked].sort().map((name) => [name, defs[name]])),
  }
}

function main() {
  const dir = identityDir()
  const path = join(dir, 'contract', 'contract.json')
  if (!existsSync(path)) {
    console.error(`schema: hdtp-identity is not at ${dir} (set HDTP_IDENTITY_DIR): the schema is generated from its contract`)
    process.exit(2)
  }
  const contract = JSON.parse(readFileSync(path, 'utf8'))
  const check = process.argv.includes('--check')
  const problems = []
  for (const version of [...versions(root), 'draft']) {
    const file = join(root, 'schema', version, 'schema.json')
    const text = JSON.stringify(schemaFor(contract, version), null, 2) + '\n'
    if (check) {
      if (!existsSync(file) || readFileSync(file, 'utf8') !== text) problems.push(`schema/${version}/schema.json is not what the contract generates: run node schema/gen.mjs`)
    } else {
      mkdirSync(join(root, 'schema', version), { recursive: true })
      writeFileSync(file, text)
      console.log(`wrote schema/${version}/schema.json`)
    }
  }
  if (problems.length) {
    console.error('schema:\n  ' + problems.join('\n  '))
    process.exit(1)
  }
  if (check) console.log(`schema: ok (${OBJECTS.length} objects, from ${path})`)
}

main()
