// The schema reference: schema/<version>/reference.md, one section per definition of
// schema/<version>/schema.json, generated from that file and from nothing else.
//
//   node schema/reference.mjs           write schema/<version>/reference.md for every version directory
//   node schema/reference.mjs --check   regenerate and fail if a committed file differs
//
// schema.json is itself generated (schema/gen.mjs, from hdtp-identity's contract), so the page is two
// steps from the contract and is never edited by hand. The check needs no sibling checkout.
import { existsSync, readdirSync, readFileSync, writeFileSync } from 'node:fs'
import { join } from 'node:path'
import { root } from '../site/spec-source.mjs'

// Every version directory of schema/ that holds a schema.json: the released versions and the draft.
const versions = () => readdirSync(join(root, 'schema'), { withFileTypes: true })
  .filter((e) => e.isDirectory() && existsSync(join(root, 'schema', e.name, 'schema.json'))).map((e) => e.name).sort()

const code = (s) => '`' + String(s).replace(/`/g, '\\`') + '`'
const cell = (s) => String(s).replace(/\|/g, '\\|').replace(/\n+/g, ' ')
const anchor = (name) => name.toLowerCase()

// A schema node, as a reader of the table needs it: its type, and what bounds it.
function typeOf(node) {
  if (node.$ref) {
    const name = node.$ref.replace('#/$defs/', '')
    return `[${code(name)}](#${anchor(name)})`
  }
  if (node.oneOf) return node.oneOf.map(typeOf).join(' or ')
  if (node.const !== undefined) return `${code(JSON.stringify(node.const))}`
  if (node.enum) return node.enum.map((v) => code(JSON.stringify(v))).join(' | ')
  if (Array.isArray(node.type)) return node.type.map((t) => code(t)).join(' or ')
  if (node.type === 'array') return `array of ${node.items ? typeOf(node.items) : 'any'}`
  if (node.type) return code(node.type)
  return 'any'
}

function boundsOf(node) {
  const out = []
  if (node.pattern) out.push(`pattern ${code(node.pattern)}`)
  if (node.minLength !== undefined) out.push(`at least ${node.minLength} characters`)
  if (node.maxLength !== undefined) out.push(`at most ${node.maxLength} characters`)
  if (node.minimum !== undefined) out.push(`≥ ${node.minimum}`)
  if (node.maximum !== undefined) out.push(`≤ ${node.maximum}`)
  if (node.minItems !== undefined) out.push(`at least ${node.minItems} items`)
  if (node.maxItems !== undefined) out.push(`at most ${node.maxItems} items`)
  return out.join('; ')
}

function section(name, def) {
  const lines = [`## ${code(name)}`, '']
  if (def.description) lines.push(def.description, '')
  if (def.type === 'object' && def.properties) {
    const required = new Set(def.required ?? [])
    lines.push('| Member | Type | Required | Bounds | Description |', '|---|---|---|---|---|')
    for (const [member, node] of Object.entries(def.properties)) {
      const nested = node.type === 'object' && node.properties
        ? ` Members: ${Object.entries(node.properties).map(([k, v]) => `${code(k)} (${typeOf(v)}${(node.required ?? []).includes(k) ? '' : ', optional'})`).join(', ')}${node.additionalProperties === false ? '; no others' : ''}.`
        : ''
      lines.push(`| ${code(member)} | ${cell(typeOf(node))} | ${required.has(member) ? 'yes' : 'no'} | ${cell(boundsOf(node))} | ${cell((node.description ?? '') + nested)} |`)
    }
    lines.push('')
    if (def.additionalProperties === false) lines.push('No other members are allowed.', '')
  } else {
    const b = boundsOf(def)
    lines.push(`Type: ${typeOf(def.$ref ? def : def)}${b ? `; ${b}` : ''}.`, '')
  }
  return lines.join('\n')
}

export function referenceFor(schema, version) {
  const names = Object.keys(schema.$defs)
  return [
    `# HDTP ${version}: schema reference`,
    '',
    `Generated by \`schema/reference.mjs\` from \`schema/${version}/schema.json\` (${code(schema.$id)}); do not edit. ` +
      'The schema is JSON Schema draft 2020-12, generated from the contract hdtp-identity validates both of its ports against; `schema/README.md` says what it covers and what it leaves out. ' +
      `An example of each object is in \`schema/${version}/examples/\`, validated against this schema.`,
    '',
    names.map((n) => `- [${code(n)}](#${anchor(n)})`).join('\n'),
    '',
    ...names.map((n) => section(n, schema.$defs[n])),
  ].join('\n')
}

function main() {
  const check = process.argv.includes('--check')
  const stale = []
  for (const version of versions()) {
    const path = join(root, 'schema', version, 'schema.json')
    if (!existsSync(path)) { stale.push(`schema/${version}/schema.json is missing`); continue }
    const want = referenceFor(JSON.parse(readFileSync(path, 'utf8')), version)
    const out = join(root, 'schema', version, 'reference.md')
    if (check) {
      if (!existsSync(out) || readFileSync(out, 'utf8') !== want) stale.push(`schema/${version}/reference.md differs from what schema.json generates (node schema/reference.mjs)`)
    } else writeFileSync(out, want)
  }
  if (stale.length) { for (const s of stale) console.error('schema reference: ' + s); process.exit(1) }
  console.log(`schema reference: ${check ? 'ok' : 'written'} (${versions().join(', ')})`)
}

main()
